config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  # get 'users/show'
  devise_for :users
  root 'books#index'

  resources :books, only: [:new, :create, :index, :show, :destroy]
  resources :users, only: [:show, :edit]
=======
  devise_for :users

  root 'books#index'

  resources :books, only: [:new, :create, :index, :show, :destroy]
  resources :books, only: [:new, :create, :index, :show, :destroy]


>>>>>>> origin/master
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

<<<<<<< HEAD
    belongs_to :user

    validates :name, presence: true
    validates :title, presence: true

end
=======
  belongs_to :user

end
>>>>>>> origin/master

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

<<<<<<< HEAD
  has_many :books, dependent: :destroy
=======
  has_many :post_images, dependent: :destroy
>>>>>>> origin/master

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
<<<<<<< HEAD
    before_action :authenticate_user!
end
=======

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end
>>>>>>> origin/master

app/controllers/books_controller.rb
class BooksController < ApplicationController

<<<<<<< HEAD
    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @books.save
            redirect_to books_path
        else
            render :new
        end
    end

    def index
        @books = Book.all
    end

    def show
        @book = Book.find(params[:id])
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

    private
        def book_params
            params.require(:book).permit(:title, :body)
        end
=======
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
  end

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
        params.require(:book).permit(:title, :body)
    end
>>>>>>> origin/master

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<<<<<<< HEAD
<section class="slice slice-lg sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-3 col-md-5">

        <div class="form-user style-1 rounded has-shadow-1">
          <div class="form-header">
            <h1 class="form-header-title">welcome to <br><span class="glyphicon glyphicon-book">
            </span>Bookers !!</h1>
          </div>
          <div class="form-body">
            <p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p>about varioius books!</p>
          </div>
          <div class="form-form">
            <div class="btn-wrapper">
              <div class="row">
                <p><%= link_to "Log in", user_session_PATH %></p>
                <p><%= link_to "Sign Up", new_user_registration_PATH %></p>
              </div>
            </div>
          </div>
=======
<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2">
        <div class="masonry-wrapper-cols">
          <div class="masonry-gutter"></div>
            <% @books.each do |book| %>
            <div class="masonry-block">
              <div class="block block-image v1">
                <div class="block-image">
                  <div class="view view-first">
                    <%= attachment_image_tag book, :image %>
                  </div>
                </div>
                <div class="block-content">
                  <%= image_tag('sample-author1.jpg', class: "img-circle pull-left profile-thumb") %>
                  <h3 class="block-title">
                    <%= link_to book_path(book.id) do %>
                      <i class="fa fa-map-marker"></i><%= book.shop_name %>
                    <% end %>
                  </h3>
                  <p><%= book.caption %></p>
                  <ul class="inline-meta">
                    <li>By
                      <%= book.user.name %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          <% end %>
>>>>>>> origin/master
        </div>
      </div>
    </div>
  </div>
</section>

app/views/books/new.html.erb
<%= form_for(@book, url: books_path) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.attachment_field :image %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group has-icon">
        <label class="control-label sr-only">ショップ名</label>
        <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
      </div>
    </div>
    <div class="col-sm-6">
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
    </div>
  </div>
  <hr>
  <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

app/views/books/show.html.erb
<<<<<<< HEAD
<div class="row">
  <div class="col-3"


=======
  <div class="post-meta-top">
    <div class="post-image">
      <%= attachment_image_tag @book, :image %>
    </div>
    </div>
    <div class="post-content">
        <h2 class="post-title"><%= @book.shop_name %></h2>
        <ul class="meta-info-cells v4 float-wrapper">
        <li>
        <i class="fa fa-user"></i>By<a href="#">
           <%= @book.user.title %></a>
        </li>
        </ul>
        <div class="post-content-inner mt-20">
            <p><%= @book.body %></p>
        </div>
    </div>
>>>>>>> origin/master

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<<<<<<< HEAD
  </head>

  <body>
    <div id="slidemenu">
      <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" style="background-color:#000000">
        <div class="navbar-header navbar-left">
          <a class="navbar-brand" style="color:#FFF">Bookers</a>
        </div>

        <div class="slidemenu collapse navbar-collapse" id="navbarExample" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class=""><%= link_to " Home", "#", class: "glyphicon glyphicon-home" %></li>
              <li class=""><%= link_to " Users", "#", class: "glyphicon glyphicon-user" %></li>
              <li class=""><%= link_to " Books", "#", class: "glyphicon glyphicon-book" %></li>
              <li class=""><%= link_to " logout", destroy_user_session_path, class: "glyphicon glyphicon-log-in" %></li>

            <% else %>
              <li class=""><%= link_to " Home", "#", class: "glyphicon glyphicon-home" %></li>
              <li class=""><%= link_to " About", "#", class: "glyphicon glyphicon-link" %></li>
              <li class=""><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %></li>
              <li class=""><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>

            <% end %>
          </ul>
        </div>
      </nav>
    </div>

    <div style="margin-top:64px">
      <%= yield %>
    </div>
=======
    <meta name="viewport" content="width=device-width, initial-scale=">
  </head>

  <body>

    <div id="slidemenu">
      <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
        <% if user_signed_in? %>
          <li class="">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
          <li class="">
            <%= link_to '投稿フォーム', new_book_path %>
          </li>
          <li class="">
            <!-- ↓以下のコードは、5章で正しいroutingに書き直します。 -->
            <%= link_to 'マイページ', "#" %>
          </li>
        <% else %>
          <li class="">
            <%= link_to "新規登録", new_user_registration_path %>
          </li>
          <li class="">
            <%= link_to "ログイン", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>


    <%= yield %>

>>>>>>> origin/master

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-offset-8 col-xs-4">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
<<<<<<< HEAD
</html>
=======
</html>


<!--
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" style="background-color:#000000">
      <div class="navbar-header navbar-left">
        <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-Example">
        </button>
          <a class="navbar-brand" style="color:#FFF">Bookers
          </a>
      </div>
    </nav>
 -->

<!-- ここにそのまま挿入 -->

<!--
    <div class="header" id="header">
      <nav class="navbar navbar-main navbar-shadow" role="navigation" id="slide-nav">
        <div class="container relative">
          <div class="navbar-header">
            <a class="navbar-logo" href="/">
              <h4>Bookers</h4>
 -->

<!--             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button> -->
>>>>>>> origin/master

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">
          <section class="slice slice-lg sct-color-1">
            <div class="container">
              <div class="row">
                <div class="col-md-4 col-md-offset-4">
                  <div class="form-user style-1 rounded has-shadow-1">
                    <div class="form-header text-center">
                      <h2 class="form-header-title">プロフィール編集</h2>
                    </div>
                    <div class="form-body">

                      <%= form_for(@user) do |f| %>
                        <div class="form-group has-icon">
                          <label class="control-label sr-only" for="inputEmail">Name</label>
                          <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
                          <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                        </div>
                        <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                      <% end %>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-3">



    <div class="profile-container">
      <h3 class="profile-name"><%= @user.name %></h3>
      <%= image_tag('sample-author1.jpg', class: "img-circle pull-left profile-thumb", style: "width: 100px; height: 100px; margin-top: 20px;") %>
    </div>



  </div>
</div>